### ISSUE TITLE
Add support for running different bincompat application

### ISSUE THREAD

**Issue by StefanJum** [unikraft/app-elfloader#29]
Modify the [`run.yaml`](https://github.com/unikraft/app-elfloader/blob/stable/scripts/run.yaml) file to add support for running different binary compatibility application (from the [`dynamic-apps repository`](https://github.com/unikraft/dynamic-apps/)).
Follow the examples for `helloworld` and `nginx`.

You will need to add a new section to the `run.yaml` file, that will look like this:

```yaml
  - name: app-name
    rootfs: path-to-dynamic-apps-app-directory
    command: run-command
    memory: amount of memoty needed
    networking: True / False depending on the application
```

To test your changes, from the `app-elfloader` directory, first run the `generate.py` script (`./scripts/generate.py`). If all went well, you should find some scripts in the `scripts/run/` directory named `qemu-x86_64-9pfs-<appname>.sh`.
Build the elfloader by running `./scripts/build/make-qemu-x86_64-9pfs.sh`, then run `./scripts/run/qemu-x86_64-9pfs-<appname>.sh` to see if the application is working.
If the run fails, it might be because of an issue in Unikraft, unrelated to your changes, so you can submit you pull request anyway, and also submit an issue with the error to get extra points.

**Hackathon Points: 10 points for every new application**
